2.1 2.2
UIT23-Bachelor-Gruppe3/hovedoppgave-gruppe3-UIT-2023 pull request #1
Opened 2023-02-21 13:40 UTC by carlosreiakvam-uit

Enkel bevegelse for sprite i 2 dimensjoner er implementert.

- Player styres med piler eller WASD.
- I forhold til networking er det lagt opp til at man trykker "host" etter at man starter spillet.
- Unity Transport protocol er satt som "unity transport" nå istedet for "Relay Unity Transport", mistenker at dette må endres på, men trenger en demo av Unity Relay først for å skjønne det.

Skriv gjerne kommentarer under.

2023-02-21 18:53 UTC, Mikal95 approved these changes
Høres bra ut.

2023-02-22 10:27 UTC, torebjerkan530599 requested changes
Koden som står der ser grei ut men det mangler litt. Du må sjekke om den som styrer er eier av det den skal kontrollere. F.eks. før noe annet skjer i  update: 

`if(!IsOwner) return;`

Du må huske at i et script så er det kode for alle klienter, men også host. Det innebærer at vi må skille ut i koden hvem som har lov til å gjøre hva. 

I tilfelle du har gjort dette (Jeg kan ikke se det i editoren enda). Vi kan ikke bruke NetworkTransform komponenten på spillerobjektet(Player prefab) fordi Serveren vil da nekte klienter å kringkaste sin posisjon. Siden vi tar sikte på å lage et mer casual game med coop kan vi bruke 

https://github.com/Unity-Technologies/com.unity.multiplayer.samples.coop.git?path=/Packages/com.unity.multiplayer.samples.coop#main

installer skriptet ved å bruke Package Manager og add package from git URL.

Du kan også skrive inn skriptet selv som vist nederst på siden:
https://docs-multiplayer.unity3d.com/netcode/current/components/networktransform/index.html

Det var det jeg gjorde når vi testet med Relay. Dette skriptet skal erstatte NetworkTransform som man vanligvis bruker. Enda bedre hadde det vært om vi hadde brukt ServerRpc's. Men vi kan foreløpig bare gjøre det sånn siden vi vet at det virker.

Packages/com.unity.multiplayer.samples.coop/Utilities/Net/ClientAuthority/ClientNetworkTransform.cs

og knytt skriptet til spillerobjektet (Player prefab)

se også https://www.youtube.com/watch?v=3yuBOB3VrCk ved 22:20

I tillegg må vi få det til å virke med Relay, men det tar på møte med Gruppa.

2023-02-22 12:38 UTC, carlosreiakvam-uit reviewed
Fikset i møte

2023-02-22 12:41 UTC, torebjerkan530599 approved these changes
Vi har gjennomgått koden og fikk det til å fungere som ønsket

2023-02-22 12:41 UTC, merged